import { format } from "date-fns";
import {
  AlertTriangle,
  Edit2,
  FileText,
  Plus,
  Settings,
  Trash2,
  X,
} from "lucide-react";
import { useEffect, useState } from "react";
import ConfirmDialog from "../components/ConfirmDialog";
import EmployeeSearchDropdown from "../components/EmployeeSearchDropdown";
import Pagination from "../components/Pagination";
import { useAuth } from "../contexts/AuthContext";
import {
  addPenalty,
  addPenaltyTemplate,
  cleanupPenalties,
  deletePenalty,
  deletePenaltyTemplate,
  getEmployeesPaginated,
  getPenaltiesPaginated,
  getPenaltyTemplates,
  resolveAllPenalties,
  updatePenalty,
  updatePenaltyTemplate,
} from "../store/storage";
import type { Employee, Penalty, PenaltyTemplate } from "../types";

type Tab = "penalties" | "templates";

export default function PenaltyManagement() {
  const { isAdmin } = useAuth();
  const [tab, setTab] = useState<Tab>("penalties");
  const [penalties, setPenalties] = useState<Penalty[]>([]);
  const [templates, setTemplates] = useState<PenaltyTemplate[]>([]);
  const [employees, setEmployees] = useState<Employee[]>([]);

  // Penalty form
  const [showForm, setShowForm] = useState(false);
  const [filterStatus, setFilterStatus] = useState("");
  const [filterType, setFilterType] = useState("");
  const [empSearch, setEmpSearch] = useState("");
  const [page, setPage] = useState(1);
  const [totalPages, setTotalPages] = useState(1);
  const [total, setTotal] = useState(0);
  const [totalActive, setTotalActive] = useState(0);
  const [resolvingAll, setResolvingAll] = useState(false);
  const [confirmResolveAll, setConfirmResolveAll] = useState(false);
  const [confirmCleanup, setConfirmCleanup] = useState(false);
  const [cleanupDays, setCleanupDays] = useState(365);
  const [cleanupResult, setCleanupResult] = useState<string | null>(null);
  const [form, setForm] = useState({
    employeeId: "",
    date: new Date().toISOString().split("T")[0],
    type: "warning" as "warning" | "deduction" | "attendance_deduction",
    reason: "",
    description: "",
    amount: 0,
  });

  // Template form
  const [showTemplateForm, setShowTemplateForm] = useState(false);
  const [editingTemplateId, setEditingTemplateId] = useState<string | null>(
    null,
  );
  const [tplForm, setTplForm] = useState({
    name: "",
    type: "warning" as "warning" | "deduction" | "attendance_deduction",
    reason: "",
    description: "",
    amount: 0,
  });

  // Confirm dialog state
  const [confirmDeletePenalty, setConfirmDeletePenalty] = useState<
    string | null
  >(null);
  const [confirmDeleteTemplate, setConfirmDeleteTemplate] = useState<
    string | null
  >(null);

  useEffect(() => {
    reload();
  }, []);

  useEffect(() => {
    setPage(1);
  }, [filterStatus, filterType]);

  useEffect(() => {
    loadPenalties();
  }, [page, filterStatus, filterType]);

  async function loadPenalties() {
    const params: Record<string, string> = { page: String(page), limit: "30" };
    if (filterStatus) params.status = filterStatus;
    if (filterType) params.type = filterType;
    const res = await getPenaltiesPaginated(params);
    setPenalties(res.data);
    setTotalPages(res.pagination.totalPages);
    setTotal(res.pagination.total);
    const activeRes = await getPenaltiesPaginated({
      status: "active",
      limit: "1",
      page: "1",
    });
    setTotalActive(activeRes.pagination.total);
  }

  async function reload() {
    await loadPenalties();
    setTemplates(await getPenaltyTemplates());
    const res = await getEmployeesPaginated({ limit: "50", isActive: "true" });
    setEmployees(res.data);
  }

  useEffect(() => {
    if (!empSearch) return;
    const timer = setTimeout(async () => {
      const res = await getEmployeesPaginated({
        limit: "50",
        isActive: "true",
        search: empSearch,
      });
      setEmployees(res.data);
    }, 400);
    return () => clearTimeout(timer);
  }, [empSearch]);

  // ---- Penalty handlers ----
  function applyTemplate(tpl: PenaltyTemplate) {
    setForm({
      ...form,
      type: tpl.type,
      reason: tpl.reason,
      description: tpl.description,
      amount: tpl.amount || 0,
    });
    setShowForm(true);
  }

  async function handleSubmit() {
    if (!form.employeeId || !form.reason.trim()) return;
    const emp = employees.find((e) => e.id === form.employeeId);
    if (!emp) return;
    await addPenalty({
      employeeId: form.employeeId,
      employeeName: emp.name,
      date: form.date,
      type: form.type,
      reason: form.reason,
      description: form.description || form.reason,
      amount:
        form.type === "deduction"
          ? form.amount
          : form.type === "attendance_deduction"
            ? form.amount
            : undefined,
      isAutoGenerated: false,
      status: "active",
    });
    await reload();
    setShowForm(false);
    setForm({
      employeeId: "",
      date: new Date().toISOString().split("T")[0],
      type: "warning",
      reason: "",
      description: "",
      amount: 0,
    });
  }

  async function handleResolve(p: Penalty) {
    await updatePenalty(p.id, { status: "resolved" });
    await reload();
  }

  async function handleResolveAll() {
    setResolvingAll(true);
    try {
      const filters: { status?: string; type?: string } = {};
      if (filterType) filters.type = filterType;
      await resolveAllPenalties(
        Object.keys(filters).length ? filters : undefined,
      );
      await loadPenalties();
    } finally {
      setResolvingAll(false);
      setConfirmResolveAll(false);
    }
  }

  async function handleCleanup() {
    const res = await cleanupPenalties(cleanupDays);
    setCleanupResult(
      `Đã xóa ${res.deleted.toLocaleString()} vi phạm đã giải quyết (> ${res.days} ngày)`,
    );
    setConfirmCleanup(false);
    await loadPenalties();
  }
  async function handleDeletePenalty(id: string) {
    await deletePenalty(id);
    setConfirmDeletePenalty(null);
    await reload();
  }

  // ---- Template handlers ----
  function openAddTemplate() {
    setTplForm({
      name: "",
      type: "warning",
      reason: "",
      description: "",
      amount: 0,
    });
    setEditingTemplateId(null);
    setShowTemplateForm(true);
  }
  function openEditTemplate(t: PenaltyTemplate) {
    setTplForm({
      name: t.name,
      type: t.type,
      reason: t.reason,
      description: t.description,
      amount: t.amount || 0,
    });
    setEditingTemplateId(t.id);
    setShowTemplateForm(true);
  }
  async function handleTemplateSubmit() {
    if (!tplForm.name.trim() || !tplForm.reason.trim()) return;
    if (editingTemplateId) {
      await updatePenaltyTemplate(editingTemplateId, {
        ...tplForm,
        amount:
          tplForm.type === "deduction" ||
          tplForm.type === "attendance_deduction"
            ? tplForm.amount
            : undefined,
        isActive: true,
      });
    } else {
      await addPenaltyTemplate({
        ...tplForm,
        amount:
          tplForm.type === "deduction" ||
          tplForm.type === "attendance_deduction"
            ? tplForm.amount
            : undefined,
        isActive: true,
      });
    }
    await reload();
    setShowTemplateForm(false);
  }
  async function handleDeleteTemplate(id: string) {
    await deletePenaltyTemplate(id);
    setConfirmDeleteTemplate(null);
    await reload();
  }

  // penalties is already server-filtered; alias for clarity
  const filtered = penalties;

  const typeLabel: Record<string, string> = {
    warning: "Cảnh báo",
    deduction: "Phạt tiền",
    attendance_deduction: "Trừ điểm chuyên cần",
  };
  const typeStyle: Record<string, string> = {
    warning: "bg-yellow-100 text-yellow-700",
    deduction: "bg-red-100 text-red-700",
    attendance_deduction: "bg-orange-100 text-orange-700",
  };
  const statusLabel: Record<string, string> = {
    active: "Đang xử lý",
    appealed: "Đã khiếu nại",
    resolved: "Đã giải quyết",
  };
  const statusStyle: Record<string, string> = {
    active: "bg-red-100 text-red-700",
    appealed: "bg-yellow-100 text-yellow-700",
    resolved: "bg-green-100 text-green-700",
  };

  return (
    <>
      <div className="space-y-6">
        {/* Header */}
        <div className="flex items-center justify-between">
          <div className="flex items-center gap-3">
            <div className="w-10 h-10 rounded-xl bg-gradient-to-br from-red-500 to-orange-600 flex items-center justify-center shadow-lg shadow-red-200">
              <AlertTriangle className="w-5 h-5 text-white" />
            </div>
            <div>
              <h1 className="text-2xl font-bold text-gray-900">
                Vi phạm & Cảnh báo
              </h1>
              <p className="text-sm text-gray-500">
                {totalActive} vi phạm đang xử lý
              </p>
            </div>
          </div>
        </div>

        {/* Tabs */}
        <div className="flex items-center gap-1 bg-gray-100 rounded-xl p-1 w-fit">
          <button
            onClick={() => setTab("penalties")}
            className={`flex items-center gap-2 px-4 py-2 text-sm font-medium rounded-lg transition-all ${tab === "penalties" ? "bg-white shadow-sm text-gray-900" : "text-gray-500 hover:text-gray-700"}`}
          >
            <FileText className="w-4 h-4" />
            Vi phạm ({total})
          </button>
          <button
            onClick={() => setTab("templates")}
            className={`flex items-center gap-2 px-4 py-2 text-sm font-medium rounded-lg transition-all ${tab === "templates" ? "bg-white shadow-sm text-gray-900" : "text-gray-500 hover:text-gray-700"}`}
          >
            <Settings className="w-4 h-4" />
            Mẫu hình phạt ({templates.length})
          </button>
        </div>

        {/* ===== PENALTIES TAB ===== */}
        {tab === "penalties" && (
          <>
            {/* Quick apply templates */}
            {templates.length > 0 && (
              <div className="flex flex-wrap items-center gap-2">
                <span className="text-xs font-medium text-gray-400">
                  Áp dụng nhanh:
                </span>
                {templates
                  .filter((t) => t.isActive)
                  .map((t) => (
                    <button
                      key={t.id}
                      onClick={() => applyTemplate(t)}
                      className={`px-3 py-1.5 text-xs font-medium rounded-lg border transition-colors ${
                        t.type === "warning"
                          ? "border-yellow-200 bg-yellow-50 text-yellow-700 hover:bg-yellow-100"
                          : "border-red-200 bg-red-50 text-red-700 hover:bg-red-100"
                      }`}
                    >
                      {t.name}{" "}
                      {t.amount ? `(${t.amount.toLocaleString()}đ)` : ""}
                    </button>
                  ))}
              </div>
            )}

            <div className="flex items-center justify-between">
              <div className="flex items-center gap-3">
                <select
                  value={filterType}
                  onChange={(e) => setFilterType(e.target.value)}
                  className="border border-gray-200 rounded-xl px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-primary-500"
                >
                  <option value="">Tất cả loại</option>
                  <option value="warning">Cảnh báo</option>
                  <option value="deduction">Phạt tiền</option>
                  <option value="attendance_deduction">
                    Trừ điểm chuyên cần
                  </option>
                </select>
                <select
                  value={filterStatus}
                  onChange={(e) => setFilterStatus(e.target.value)}
                  className="border border-gray-200 rounded-xl px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-primary-500"
                >
                  <option value="">Tất cả trạng thái</option>
                  <option value="active">Đang xử lý</option>
                  <option value="appealed">Đã khiếu nại</option>
                  <option value="resolved">Đã giải quyết</option>
                </select>
              </div>
              <div className="flex items-center gap-2">
                {filterStatus !== "resolved" && total > 0 && (
                  <button
                    onClick={() => setConfirmResolveAll(true)}
                    disabled={resolvingAll}
                    className="flex items-center gap-2 px-4 py-2 bg-green-600 text-white text-sm font-medium rounded-xl hover:bg-green-700 transition-all shadow-sm disabled:opacity-60"
                  >
                    {resolvingAll
                      ? "Đang xử lý..."
                      : `Giải quyết tất cả (${total.toLocaleString()})`}
                  </button>
                )}
                {isAdmin && (
                  <button
                    onClick={() => setConfirmCleanup(true)}
                    className="flex items-center gap-2 px-4 py-2 bg-gray-600 text-white text-sm font-medium rounded-xl hover:bg-gray-700 transition-all shadow-sm"
                    title="Xóa vi phạm đã giải quyết cũ"
                  >
                    <Trash2 className="w-4 h-4" />
                    Dọn dẹp
                  </button>
                )}
                <button
                  onClick={() => setShowForm(!showForm)}
                  className="flex items-center gap-2 px-4 py-2 bg-gradient-to-r from-red-500 to-orange-500 text-white text-sm font-medium rounded-xl hover:from-red-600 hover:to-orange-600 transition-all shadow-sm"
                >
                  <Plus className="w-4 h-4" />
                  {showForm ? "Đóng" : "Thêm vi phạm"}
                </button>
              </div>
            </div>

            {showForm && (
              <div className="bg-white rounded-2xl border border-gray-200 shadow-sm p-5">
                <h3 className="text-sm font-bold text-gray-800 mb-4">
                  Thêm vi phạm mới
                </h3>
                <div className="grid grid-cols-1 sm:grid-cols-3 gap-4">
                  <div>
                    <label className="block text-xs font-semibold text-gray-500 uppercase tracking-wider mb-1.5">
                      Nhân viên
                    </label>
                    <EmployeeSearchDropdown
                      employees={employees}
                      value={form.employeeId}
                      onChange={(id) => setForm({ ...form, employeeId: id })}
                      onSearch={(q) => setEmpSearch(q)}
                    />
                  </div>
                  <div>
                    <label className="block text-xs font-semibold text-gray-500 uppercase tracking-wider mb-1.5">
                      Ngày
                    </label>
                    <input
                      type="date"
                      value={form.date}
                      onChange={(e) =>
                        setForm({ ...form, date: e.target.value })
                      }
                      className="w-full px-3 py-2 border border-gray-200 rounded-xl text-sm focus:outline-none focus:ring-2 focus:ring-primary-500"
                    />
                  </div>
                  <div>
                    <label className="block text-xs font-semibold text-gray-500 uppercase tracking-wider mb-1.5">
                      Loại
                    </label>
                    <select
                      value={form.type}
                      onChange={(e) =>
                        setForm({
                          ...form,
                          type: e.target.value as
                            | "warning"
                            | "deduction"
                            | "attendance_deduction",
                        })
                      }
                      className="w-full px-3 py-2 border border-gray-200 rounded-xl text-sm focus:outline-none focus:ring-2 focus:ring-primary-500"
                    >
                      <option value="warning">Cảnh báo</option>
                      <option value="deduction">Phạt tiền</option>
                      <option value="attendance_deduction">
                        Trừ điểm chuyên cần
                      </option>
                    </select>
                  </div>
                  <div className="sm:col-span-2">
                    <label className="block text-xs font-semibold text-gray-500 uppercase tracking-wider mb-1.5">
                      Lý do
                    </label>
                    <input
                      type="text"
                      value={form.reason}
                      onChange={(e) =>
                        setForm({ ...form, reason: e.target.value })
                      }
                      placeholder="Lý do vi phạm"
                      className="w-full px-3 py-2 border border-gray-200 rounded-xl text-sm focus:outline-none focus:ring-2 focus:ring-primary-500"
                    />
                  </div>
                  {(form.type === "deduction" ||
                    form.type === "attendance_deduction") && (
                    <div>
                      <label className="block text-xs font-semibold text-gray-500 uppercase tracking-wider mb-1.5">
                        {form.type === "attendance_deduction"
                          ? "Số điểm trừ"
                          : "Số tiền (VND)"}
                      </label>
                      <input
                        type="number"
                        value={form.amount}
                        onChange={(e) =>
                          setForm({ ...form, amount: Number(e.target.value) })
                        }
                        min={0}
                        className="w-full px-3 py-2 border border-gray-200 rounded-xl text-sm focus:outline-none focus:ring-2 focus:ring-primary-500"
                      />
                    </div>
                  )}
                  <div className="sm:col-span-3">
                    <label className="block text-xs font-semibold text-gray-500 uppercase tracking-wider mb-1.5">
                      Mô tả chi tiết
                    </label>
                    <textarea
                      value={form.description}
                      onChange={(e) =>
                        setForm({ ...form, description: e.target.value })
                      }
                      rows={2}
                      className="w-full px-3 py-2 border border-gray-200 rounded-xl text-sm focus:outline-none focus:ring-2 focus:ring-primary-500"
                    />
                  </div>
                </div>
                <div className="flex gap-2 mt-4">
                  <button
                    onClick={handleSubmit}
                    className="px-5 py-2 bg-gradient-to-r from-red-500 to-orange-500 text-white text-sm font-medium rounded-xl"
                  >
                    Lưu
                  </button>
                  <button
                    onClick={() => setShowForm(false)}
                    className="px-4 py-2 bg-gray-100 text-gray-600 text-sm font-medium rounded-xl hover:bg-gray-200"
                  >
                    Hủy
                  </button>
                </div>
              </div>
            )}

            {/* Penalty table */}
            <div className="bg-white rounded-2xl border border-gray-200 shadow-sm overflow-hidden">
              <Pagination
                page={page}
                totalPages={totalPages}
                total={total}
                onPageChange={setPage}
                label="vi phạm"
              />
              <div className="overflow-x-auto">
                <table className="w-full">
                  <thead>
                    <tr className="bg-gray-50 border-b border-gray-200">
                      <th className="text-left px-5 py-3 text-xs font-semibold text-gray-500 uppercase">
                        Nhân viên
                      </th>
                      <th className="text-left px-5 py-3 text-xs font-semibold text-gray-500 uppercase">
                        Ngày
                      </th>
                      <th className="text-center px-5 py-3 text-xs font-semibold text-gray-500 uppercase">
                        Loại
                      </th>
                      <th className="text-left px-5 py-3 text-xs font-semibold text-gray-500 uppercase">
                        Lý do
                      </th>
                      <th className="text-center px-5 py-3 text-xs font-semibold text-gray-500 uppercase">
                        Số tiền
                      </th>
                      <th className="text-center px-5 py-3 text-xs font-semibold text-gray-500 uppercase">
                        Nguồn
                      </th>
                      <th className="text-center px-5 py-3 text-xs font-semibold text-gray-500 uppercase">
                        Trạng thái
                      </th>
                      <th className="text-right px-5 py-3 text-xs font-semibold text-gray-500 uppercase">
                        Thao tác
                      </th>
                    </tr>
                  </thead>
                  <tbody className="divide-y divide-gray-100">
                    {filtered.length === 0 ? (
                      <tr>
                        <td
                          colSpan={8}
                          className="text-center py-12 text-gray-400"
                        >
                          Không có vi phạm
                        </td>
                      </tr>
                    ) : (
                      filtered.map((p) => (
                        <tr
                          key={p.id}
                          className="hover:bg-gray-50 transition-colors"
                        >
                          <td className="px-5 py-3 text-sm font-medium text-gray-900">
                            {p.employeeName}
                          </td>
                          <td className="px-5 py-3 text-sm text-gray-600">
                            {format(
                              new Date(p.date + "T00:00:00"),
                              "dd/MM/yyyy",
                            )}
                          </td>
                          <td className="px-5 py-3 text-center">
                            <span
                              className={`px-2 py-0.5 rounded-full text-xs font-medium ${typeStyle[p.type]}`}
                            >
                              {typeLabel[p.type]}
                            </span>
                          </td>
                          <td className="px-5 py-3 text-sm text-gray-600 max-w-[200px] truncate">
                            {p.reason}
                          </td>
                          <td className="px-5 py-3 text-center text-sm tabular-nums">
                            {p.type === "attendance_deduction" ? (
                              p.amount ? (
                                <span className="text-orange-600 font-medium">
                                  -{p.amount} điểm
                                </span>
                              ) : (
                                "—"
                              )
                            ) : p.amount ? (
                              `${p.amount.toLocaleString()}đ`
                            ) : (
                              "—"
                            )}
                          </td>
                          <td className="px-5 py-3 text-center">
                            <span
                              className={`text-xs ${p.isAutoGenerated ? "text-purple-600" : "text-gray-500"}`}
                            >
                              {p.isAutoGenerated ? "Tự động" : "Thủ công"}
                            </span>
                          </td>
                          <td className="px-5 py-3 text-center">
                            <span
                              className={`px-2 py-0.5 rounded-full text-xs font-medium ${statusStyle[p.status]}`}
                            >
                              {statusLabel[p.status]}
                            </span>
                          </td>
                          <td className="px-5 py-3 text-right">
                            <div className="flex items-center justify-end gap-1">
                              {p.status === "active" && (
                                <button
                                  onClick={() => handleResolve(p)}
                                  className="px-2 py-1 rounded-lg hover:bg-green-50 text-xs text-green-600 font-medium"
                                >
                                  Giải quyết
                                </button>
                              )}
                              <button
                                onClick={() => setConfirmDeletePenalty(p.id)}
                                className="px-2 py-1 rounded-lg hover:bg-red-50 text-xs text-red-600 font-medium"
                              >
                                Xóa
                              </button>
                            </div>
                          </td>
                        </tr>
                      ))
                    )}
                  </tbody>
                </table>
              </div>
              <Pagination
                page={page}
                totalPages={totalPages}
                total={total}
                onPageChange={setPage}
                label="vi phạm"
              />
            </div>
          </>
        )}

        {/* ===== TEMPLATES TAB ===== */}
        {tab === "templates" && (
          <>
            <div className="flex items-center justify-end">
              <button
                onClick={openAddTemplate}
                className="flex items-center gap-2 px-4 py-2 bg-gradient-to-r from-indigo-500 to-indigo-600 text-white text-sm font-medium rounded-xl hover:from-indigo-600 hover:to-indigo-700 transition-all shadow-sm"
              >
                <Plus className="w-4 h-4" />
                Thêm mẫu hình phạt
              </button>
            </div>

            {showTemplateForm && (
              <div className="bg-white rounded-2xl border border-gray-200 shadow-sm overflow-hidden">
                <div className="flex items-center justify-between px-5 py-3 bg-gradient-to-r from-indigo-50 to-white border-b border-gray-100">
                  <h3 className="text-sm font-bold text-gray-800">
                    {editingTemplateId
                      ? "Sửa mẫu hình phạt"
                      : "Thêm mẫu hình phạt mới"}
                  </h3>
                  <button
                    onClick={() => setShowTemplateForm(false)}
                    className="p-1 rounded-lg hover:bg-gray-100 text-gray-400"
                  >
                    <X className="w-4 h-4" />
                  </button>
                </div>
                <div className="p-5 space-y-4">
                  <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                    <div>
                      <label className="block text-xs font-semibold text-gray-500 uppercase tracking-wider mb-1.5">
                        Tên mẫu *
                      </label>
                      <input
                        type="text"
                        value={tplForm.name}
                        onChange={(e) =>
                          setTplForm({ ...tplForm, name: e.target.value })
                        }
                        placeholder="VD: Đi muộn"
                        className="w-full px-3 py-2 border border-gray-200 rounded-xl text-sm focus:outline-none focus:ring-2 focus:ring-indigo-500"
                      />
                    </div>
                    <div>
                      <label className="block text-xs font-semibold text-gray-500 uppercase tracking-wider mb-1.5">
                        Loại
                      </label>
                      <select
                        value={tplForm.type}
                        onChange={(e) =>
                          setTplForm({
                            ...tplForm,
                            type: e.target.value as
                              | "warning"
                              | "deduction"
                              | "attendance_deduction",
                          })
                        }
                        className="w-full px-3 py-2 border border-gray-200 rounded-xl text-sm focus:outline-none focus:ring-2 focus:ring-indigo-500"
                      >
                        <option value="warning">Cảnh báo</option>
                        <option value="deduction">Phạt tiền</option>
                        <option value="attendance_deduction">
                          Trừ điểm chuyên cần
                        </option>
                      </select>
                    </div>
                  </div>
                  <div>
                    <label className="block text-xs font-semibold text-gray-500 uppercase tracking-wider mb-1.5">
                      Lý do mặc định *
                    </label>
                    <input
                      type="text"
                      value={tplForm.reason}
                      onChange={(e) =>
                        setTplForm({ ...tplForm, reason: e.target.value })
                      }
                      className="w-full px-3 py-2 border border-gray-200 rounded-xl text-sm focus:outline-none focus:ring-2 focus:ring-indigo-500"
                    />
                  </div>
                  <div>
                    <label className="block text-xs font-semibold text-gray-500 uppercase tracking-wider mb-1.5">
                      Mô tả
                    </label>
                    <textarea
                      value={tplForm.description}
                      onChange={(e) =>
                        setTplForm({ ...tplForm, description: e.target.value })
                      }
                      rows={2}
                      className="w-full px-3 py-2 border border-gray-200 rounded-xl text-sm focus:outline-none focus:ring-2 focus:ring-indigo-500"
                    />
                  </div>
                  {(tplForm.type === "deduction" ||
                    tplForm.type === "attendance_deduction") && (
                    <div>
                      <label className="block text-xs font-semibold text-gray-500 uppercase tracking-wider mb-1.5">
                        {tplForm.type === "attendance_deduction"
                          ? "Số điểm trừ mặc định"
                          : "Số tiền mặc định (VND)"}
                      </label>
                      <input
                        type="number"
                        value={tplForm.amount}
                        onChange={(e) =>
                          setTplForm({
                            ...tplForm,
                            amount: Number(e.target.value),
                          })
                        }
                        min={0}
                        className="w-full px-3 py-2 border border-gray-200 rounded-xl text-sm focus:outline-none focus:ring-2 focus:ring-indigo-500"
                      />
                    </div>
                  )}
                  <div className="flex gap-2">
                    <button
                      onClick={handleTemplateSubmit}
                      className="px-5 py-2 bg-gradient-to-r from-indigo-500 to-indigo-600 text-white text-sm font-medium rounded-xl"
                    >
                      {editingTemplateId ? "Cập nhật" : "Thêm"}
                    </button>
                    <button
                      onClick={() => setShowTemplateForm(false)}
                      className="px-4 py-2 bg-gray-100 text-gray-600 text-sm font-medium rounded-xl hover:bg-gray-200"
                    >
                      Hủy
                    </button>
                  </div>
                </div>
              </div>
            )}

            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
              {templates.map((t) => (
                <div
                  key={t.id}
                  className={`bg-white rounded-2xl border shadow-sm p-5 ${t.type === "warning" ? "border-yellow-200" : "border-red-200"}`}
                >
                  <div className="flex items-start justify-between mb-3">
                    <div>
                      <span
                        className={`inline-block px-2 py-0.5 rounded-full text-xs font-medium mb-2 ${typeStyle[t.type]}`}
                      >
                        {typeLabel[t.type]}
                      </span>
                      <h3 className="text-sm font-bold text-gray-900">
                        {t.name}
                      </h3>
                    </div>
                    <div className="flex gap-1">
                      <button
                        onClick={() => openEditTemplate(t)}
                        className="p-1.5 rounded-lg hover:bg-gray-100 text-gray-400"
                      >
                        <Edit2 className="w-3.5 h-3.5" />
                      </button>
                      <button
                        onClick={() => setConfirmDeleteTemplate(t.id)}
                        className="p-1.5 rounded-lg hover:bg-red-50 text-gray-400 hover:text-red-600"
                      >
                        <Trash2 className="w-3.5 h-3.5" />
                      </button>
                    </div>
                  </div>
                  <p className="text-xs text-gray-500 mb-2">{t.reason}</p>
                  {t.description && (
                    <p className="text-[11px] text-gray-400 mb-2">
                      {t.description}
                    </p>
                  )}
                  {t.amount && (
                    <p className="text-sm font-semibold text-red-600">
                      {t.amount.toLocaleString()}đ
                    </p>
                  )}
                </div>
              ))}
            </div>

            {templates.length === 0 && (
              <div className="text-center py-16 text-gray-400">
                <Settings className="w-12 h-12 mx-auto mb-3 opacity-30" />
                <p className="text-sm">Chưa có mẫu hình phạt</p>
                <button
                  onClick={openAddTemplate}
                  className="mt-2 text-sm text-indigo-600 hover:underline"
                >
                  Thêm mẫu đầu tiên →
                </button>
              </div>
            )}
          </>
        )}
      </div>

      <ConfirmDialog
        open={!!confirmDeletePenalty}
        title="Xóa vi phạm"
        message="Bạn có chắc muốn xóa vi phạm này?"
        confirmLabel="Xóa"
        onConfirm={() =>
          confirmDeletePenalty && handleDeletePenalty(confirmDeletePenalty)
        }
        onCancel={() => setConfirmDeletePenalty(null)}
      />
      <ConfirmDialog
        open={!!confirmDeleteTemplate}
        title="Xóa mẫu hình phạt"
        message="Bạn có chắc muốn xóa mẫu hình phạt này?"
        confirmLabel="Xóa"
        onConfirm={() =>
          confirmDeleteTemplate && handleDeleteTemplate(confirmDeleteTemplate)
        }
        onCancel={() => setConfirmDeleteTemplate(null)}
      />

      {/* Confirm: resolve all */}
      {confirmResolveAll && (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/40">
          <div className="bg-white rounded-2xl shadow-xl w-full max-w-sm mx-4 p-6">
            <h3 className="text-base font-semibold text-gray-900 mb-2">
              Giải quyết tất cả vi phạm?
            </h3>
            <p className="text-sm text-gray-600 mb-4">
              Toàn bộ <strong>{total.toLocaleString()}</strong> vi phạm
              {filterType ? ` loại "${filterType}"` : ""}
              {filterStatus ? ` trạng thái "${filterStatus}"` : ""}
              &nbsp;sẽ được đánh dấu{" "}
              <span className="text-green-700 font-medium">Đã giải quyết</span>.
            </p>
            <div className="flex justify-end gap-3">
              <button
                onClick={() => setConfirmResolveAll(false)}
                className="px-4 py-2 text-sm text-gray-600 border border-gray-200 rounded-lg hover:bg-gray-50"
              >
                Hủy
              </button>
              <button
                onClick={handleResolveAll}
                disabled={resolvingAll}
                className="px-4 py-2 text-sm bg-green-600 text-white rounded-lg hover:bg-green-700 disabled:opacity-60"
              >
                {resolvingAll ? "Đang xử lý..." : "Xác nhận"}
              </button>
            </div>
          </div>
        </div>
      )}

      {/* Confirm: cleanup */}
      {confirmCleanup && (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/40">
          <div className="bg-white rounded-2xl shadow-xl w-full max-w-sm mx-4 p-6">
            <h3 className="text-base font-semibold text-gray-900 mb-2">
              Dọn dẹp vi phạm cũ
            </h3>
            <p className="text-sm text-gray-600 mb-4">
              Xóa vĩnh viễn tất cả vi phạm <strong>đã giải quyết</strong> cũ
              hơn:
            </p>
            <div className="flex items-center gap-3 mb-4">
              <select
                value={cleanupDays}
                onChange={(e) => setCleanupDays(Number(e.target.value))}
                className="flex-1 border border-gray-200 rounded-lg px-3 py-2 text-sm"
              >
                <option value={90}>90 ngày (3 tháng)</option>
                <option value={180}>180 ngày (6 tháng)</option>
                <option value={365}>365 ngày (1 năm) — khuyến nghị</option>
                <option value={730}>730 ngày (2 năm)</option>
              </select>
            </div>
            <p className="text-xs text-red-600 bg-red-50 rounded-lg px-3 py-2 mb-4">
              ⚠ Thao tác này không thể hoàn tác. Dữ liệu sẽ bị xóa vĩnh viễn.
            </p>
            <div className="flex justify-end gap-3">
              <button
                onClick={() => setConfirmCleanup(false)}
                className="px-4 py-2 text-sm text-gray-600 border border-gray-200 rounded-lg hover:bg-gray-50"
              >
                Hủy
              </button>
              <button
                onClick={handleCleanup}
                className="px-4 py-2 text-sm bg-red-600 text-white rounded-lg hover:bg-red-700"
              >
                Xóa dữ liệu cũ
              </button>
            </div>
          </div>
        </div>
      )}

      {/* Cleanup result toast */}
      {cleanupResult && (
        <div className="fixed bottom-6 right-6 z-50 bg-gray-900 text-white text-sm px-4 py-3 rounded-xl shadow-lg flex items-center gap-3">
          {cleanupResult}
          <button
            onClick={() => setCleanupResult(null)}
            className="text-gray-400 hover:text-white"
          >
            &times;
          </button>
        </div>
      )}
    </>
  );
}
