// ==================== Employee ====================
export interface Employee {
  id: string;
  name: string;
  employeeCode: string;
  department: string;
  departmentId?: string;
  position: string;
  roleLevel: number; // 1=Admin, 2=GĐ, 3=TP/PP, 4=Tổ trưởng, 5=NV
  email: string;
  phone: string;
  avatar?: string;
  faceDescriptor?: Float32Array;
  faceImage?: string;
  createdAt: string;
  isActive: boolean;
}

// ==================== Shift Master ====================
export interface Shift {
  id: string;
  name: string;
  startTime: string; // HH:mm
  endTime: string;   // HH:mm
  color: string;
  allowLateMinutes: number;
  allowEarlyLeaveMinutes: number;
  breakStartTime?: string; // HH:mm
  breakEndTime?: string;   // HH:mm
  isOvernight: boolean;    // ca qua đêm
}

// ==================== Shift Assignment / Rostering ====================
export interface ShiftAssignment {
  id: string;
  employeeId: string;
  shiftId: string;
  dayOfWeek: number; // 0=Sunday ... 6=Saturday
  effectiveFrom: string;
  effectiveTo?: string;
}

// ==================== Attendance ====================
export interface AttendanceRecord {
  id: string;
  employeeId: string;
  employeeName: string;
  date: string; // YYYY-MM-DD
  shiftId: string;
  shiftName: string;
  checkInTime?: string;
  checkOutTime?: string;
  checkInImage?: string;
  checkOutImage?: string;
  status: AttendanceStatus;
  lateMinutes: number;
  earlyLeaveMinutes: number;
  workingHours: number;
  note?: string;
}

export type AttendanceStatus =
  | 'on-time'
  | 'late'
  | 'early-leave'
  | 'absent'
  | 'pending';

// ==================== OT (Overtime) ====================
export interface OTRequest {
  id: string;
  employeeId: string;
  employeeName: string;
  date: string;
  shiftId: string;
  startTime: string; // HH:mm
  endTime: string;
  hours: number;
  multiplier: number; // 1.5, 2.0, 3.0
  reason: string;
  status: 'pending' | 'approved' | 'rejected';
  approvedBy?: string;
  approvedAt?: string;
  createdAt: string;
}

// ==================== Audit Log ====================
export interface AuditLog {
  id: string;
  timestamp: string;
  action: 'check-in' | 'check-out' | 'correction' | 'ot-request' | 'ot-approve' | 'ot-reject' | 'shift-swap' | 'leave-request' | 'penalty';
  performedBy: string; // employee name or 'System'
  targetEmployee?: string;
  details: string;
  oldValue?: string;
  newValue?: string;
}

// ==================== Time Correction ====================
export interface TimeCorrection {
  id: string;
  attendanceId: string;
  employeeId: string;
  employeeName: string;
  date: string;
  field: 'checkInTime' | 'checkOutTime';
  oldValue: string;
  newValue: string;
  reason: string;
  status: 'pending' | 'approved' | 'rejected';
  requestedAt: string;
  approvedBy?: string;
  approvedAt?: string;
}

// ==================== Penalty / Warning ====================
export interface Penalty {
  id: string;
  employeeId: string;
  employeeName: string;
  date: string;
  type: 'warning' | 'deduction' | 'attendance_deduction';
  reason: string;
  amount?: number;       // tiền phạt (nếu deduction)
  description: string;
  isAutoGenerated: boolean;
  status: 'active' | 'appealed' | 'resolved';
  appealReason?: string;
  createdAt: string;
}

// ==================== Shift Swap ====================
export interface ShiftSwapRequest {
  id: string;
  requesterId: string;
  requesterName: string;
  targetId: string;
  targetName: string;
  date: string;
  requesterShiftId: string;
  targetShiftId: string;
  reason: string;
  status: 'pending' | 'accepted' | 'rejected';
  createdAt: string;
}

// ==================== Holiday / Leave ====================
export interface Holiday {
  id: string;
  name: string;
  date: string;
  type: 'public' | 'company';
}

export interface LeaveRequest {
  id: string;
  employeeId: string;
  employeeName: string;
  startDate: string;
  endDate: string;
  type: 'annual' | 'sick' | 'personal' | 'maternity' | 'unpaid' | 'hourly';
  hours?: number; // For hourly leave type
  reason: string;
  status: 'pending' | 'approved' | 'rejected';
  createdAt: string;
  approvedBy?: string;
}

// ==================== Monthly Timesheet ====================
export interface MonthlyTimesheet {
  employeeId: string;
  employeeName: string;
  month: string; // YYYY-MM
  totalWorkDays: number;
  presentDays: number;
  absentDays: number;
  lateDays: number;
  earlyLeaveDays: number;
  totalWorkingHours: number;
  totalOTHours: number;
  leaveDays: number;
  onTimeRate: number;
  isLocked: boolean;
  lockedAt?: string;
  lockedBy?: string;
}

// ==================== Dashboard ====================
export interface DashboardStats {
  totalEmployees: number;
  presentToday: number;
  lateToday: number;
  absentToday: number;
  earlyLeaveToday: number;
  onTimeRate: number;
  avgWorkingHours: number;
  pendingOT: number;
  pendingLeave: number;
}

// ==================== Role Levels ====================
export const ROLE_LEVELS = {
  ADMIN: 1,
  DIRECTOR: 2,     // Tổng giám đốc / Giám đốc đơn vị
  MANAGER: 3,      // Trưởng phòng / Phó phòng
  TEAM_LEAD: 4,    // Tổ trưởng
  EMPLOYEE: 5,     // Nhân viên
} as const;

export const ROLE_LEVEL_LABELS: Record<number, string> = {
  1: 'Admin',
  2: 'Giám đốc',
  3: 'Trưởng/Phó phòng',
  4: 'Tổ trưởng',
  5: 'Nhân viên',
};

// ==================== User / Auth ====================
export interface User {
  id: string;
  employeeId?: string; // linked employee (for 'user' role)
  username: string;
  password: string; // plain for demo
  name: string;
  role: 'admin' | 'user';
  roleLevel: number; // 1=Admin, 2=GD, 3=TP/PP, 4=Tổ trưởng, 5=NV
  roles?: string[]; // additional roles: 'salary_manager', etc.
  department?: string;
  avatar?: string;
}

// ==================== Company Location (GPS) ====================
export interface CompanyLocation {
  id: string;
  name: string;
  address: string;
  latitude: number;
  longitude: number;
  radius: number; // meters — allowed check-in radius
}

// ==================== Department ====================
export interface Department {
  id: string;
  name: string;
  description?: string;
  managerId?: string; // employeeId of dept head
  managerName?: string;
  parentId?: string; // for tree structure
  memberCount?: number;
  createdAt: string;
}

// ==================== Penalty Template ====================
export interface PenaltyTemplate {
  id: string;
  name: string;
  type: 'warning' | 'deduction' | 'attendance_deduction';
  reason: string;
  description: string;
  amount?: number; // default amount for deduction
  isActive: boolean;
  createdAt: string;
}

// ==================== Salary ====================
export interface SalaryPreset {
  id: string;
  name: string;
  description: string;
  baseSalary: number;
  formulaType: 'standard' | 'custom';
  /**
   * Standard formula:
   *   netSalary = baseSalary / totalWorkDays * presentDays
   *             + otHours * (baseSalary / totalWorkDays / 8) * otMultiplier
   *             - totalDeductions
   *             + allowances
   *
   * Custom formula:  user-entered JS expression string
   */
  customFormula?: string; // JS expression: vars → base, workDays, present, otHours, otRate, deductions, allowances, late, earlyLeave
  allowances: number;
  isDefault: boolean;
  createdAt: string;
}

export interface EmployeeSalaryAssignment {
  employeeId: string;
  presetId: string;
}

export interface SalaryRecord {
  id: string;
  employeeId: string;
  employeeName: string;
  employeeCode?: string;
  department?: string;
  position?: string;
  month: string; // YYYY-MM
  presetId: string;
  presetName: string;
  baseSalary: number;
  totalWorkDays: number;
  presentDays: number;
  totalWorkingHours?: number;
  otHours: number;
  otPay: number;
  allowances: number;
  deductions: number;
  latePenalty: number;
  grossSalary: number;
  netSalary: number;
  calculatedAt: string;
}
